spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.82.82.161:3306/database?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    initialize: true
    #schema: classpath:schema.sql #初始化数据表
    username: root
    password: 123456
  jpa:
    hibernate:
      #create 程序运行时 重新创建一张表
      #update 创建表 但不会删除表中的数据
      #create-drop 应用停止时， 删除表
      #none
      #validate 验证类中的属性是否与表结构一致，不一致 会报错
      ddl-auto: update
    show-sql: true